# Generated by Django 3.1.3 on 2020-12-29 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='provider_individ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('kind_of_activity', models.CharField(max_length=200)),
                ('VAT_payer', models.CharField(max_length=200)),
                ('count_of_outlets', models.CharField(max_length=200)),
                ('trading_area', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('delivery', models.CharField(max_length=200)),
                ('deferment_of_payment', models.CharField(max_length=200)),
                ('certificate_of_registration', models.CharField(max_length=200)),
                ('payment_form', models.CharField(max_length=200)),
                ('min_order', models.CharField(max_length=200)),
                ('warranty', models.CharField(max_length=200)),
                ('availability_of_certificates', models.CharField(max_length=200)),
                ('short_desc', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='provider_entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('kind_of_activity', models.CharField(max_length=200)),
                ('VAT_payer', models.CharField(max_length=200)),
                ('count_of_outlets', models.CharField(max_length=200)),
                ('trading_area', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('delivery', models.CharField(max_length=200)),
                ('deferment_of_payment', models.CharField(max_length=200)),
                ('certificate_of_registration', models.CharField(max_length=200)),
                ('payment_form', models.CharField(max_length=200)),
                ('min_order', models.CharField(max_length=200)),
                ('warranty', models.CharField(max_length=200)),
                ('availability_of_certificates', models.CharField(max_length=200)),
                ('inn', models.CharField(max_length=200)),
                ('short_desc', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='buyer_entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('kind_of_activity', models.CharField(max_length=200)),
                ('VAT_payer', models.CharField(max_length=200)),
                ('count_of_outlets', models.CharField(max_length=200)),
                ('trading_area', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('inn', models.CharField(max_length=200)),
                ('short_desc', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
