# Generated by Django 3.1.3 on 2021-01-07 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_buyer_entity_provider_entity_provider_individ'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='provider_individ',
            name='count_of_outlets',
        ),
        migrations.RemoveField(
            model_name='provider_individ',
            name='payment_form',
        ),
        migrations.RemoveField(
            model_name='provider_individ',
            name='trading_area',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comments', to='accounts.document')),
            ],
        ),
    ]
