# Generated by Django 3.1.3 on 2021-01-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210107_0504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message_to_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Document',
            new_name='Complaint',
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='Payment_detail',
        ),
    ]
