# Generated by Django 3.1.7 on 2021-03-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_massage_to_admin_paymentdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('expiration', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=3)),
            ],
        ),
    ]
